org: yeukfei02
app: random-joke-slack-serverless
service: random-joke-slack-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1
  environment:
    NODE_ENV: production
    SLACK_OAUTH_TOKEN: ${param:SLACK_OAUTH_TOKEN}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

functions:
  main:
    handler: src/getMain/handler.getMain
    tracing: true
    events:
      - http:
          path: /api/joke
          method: get
          cors: true

  getJoke:
    handler: src/getJoke/handler.getJoke
    tracing: true
    events:
      - http:
          path: /api/joke/get-joke
          method: post
          cors: true

  getJokeByType:
    handler: src/getJokeByType/handler.getJokeByType
    tracing: true
    events:
      - http:
          path: /api/joke/get-joke-by-type
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-split-stacks
