org: yeukfei02
app: random-joke-slack-serverless
service: random-joke-slack-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: v1
  region: ap-southeast-1
  environment:
    NODE_ENV: production

functions:
  getJoke:
    handler: src/getJoke/handler.getJoke
    events:
      - http:
          path: /api/joke/get-joke
          method: post
          cors: true
  
  getJokeByType:
    handler: src/getJokeByType/handler.getJokeByType
    events:
      - http:
          path: /api/joke/get-joke-by-type
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
