org: yeukfei05
app: random-joke-slack-serverless
service: random-joke-slack-serverless

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-southeast-1
  apiName: random-joke-slack-serverless-prod
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: production
    SLACK_OAUTH_TOKEN: ${param:SLACK_OAUTH_TOKEN}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: random joke slack serverless prod
  architecture: arm64
  timeout: 30

functions:
  main:
    handler: src/getMain/handler.getMain
    events:
      - http:
          path: /api/joke
          method: get
          cors: true

  getJoke:
    handler: src/getJoke/handler.getJoke
    events:
      - http:
          path: /api/joke/get-joke
          method: post
          cors: true

  getJokeByType:
    handler: src/getJokeByType/handler.getJokeByType
    events:
      - http:
          path: /api/joke/get-joke-by-type
          method: post
          cors: true

plugins:
  - serverless-layers
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-layers:
    - common:
        packageManager: yarn
        dependenciesPath: ./package.json
        layersDeploymentBucket: random-joke-slack-serverless-serverless-layers
